version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '10:00'
      timezone: 'Asia/Tokyo'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '10:00'
      timezone: 'Asia/Tokyo'

    open-pull-requests-limit: 10
    target-branch: 'dev'
    versioning-strategy: auto
    labels:
      - 'dependencies'
      - 'npm'
